version: '3.8'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-container-eventproject
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: event_project_api_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - ./db/data:/var/lib/mysql